version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_mmo
    restart: always
    environment:
      POSTGRES_USER: mmo_user
      POSTGRES_PASSWORD: mmo_password
      POSTGRES_DB: mixsource
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
